#!/usr/bin/env bash

Info="\033[32m[信息]\033[0m"
Error="\033[31m[错误]\033[0m"
Warning="\033[33m[警告]\033[0m"
Tip="\033[32m[注意]\033[0m"

# 提示用户输入 username 和 password
read -p "请输入用户名: " username
read -p "请输入密码: " password
echo

# 提供一个 domain 列表供用户选择
echo "请选择一个域名:"
domains=("aws.kissnb.cc" "tz.kisssik.top" "vultr.kissnb.cc" "az100.kisssik.top")
select domain in "${domains[@]}"; do
    if [[ -n "$domain" ]]; then
        break
    else
        echo "无效选择，请重试。"
    fi
done

# 构造 UPM 参数
UPM="https://$username:$password@$domain"

mkdir -p /opt/ServerStatus/client
mkdir -p /opt/ServerStatus/server

# 调用原脚本，并传递参数
bash <(curl -s -S -L https://raw.githubusercontent.com/zdz/ServerStatus-Rust/master/scripts/status.sh) -i -c "$UPM"

sleep 1
echo -e "${Info} 重启"
systemctl restart stat_client.service
