version: '3'
services:
  redis:
    image: redis:latest
    restart: unless-stopped
  web:
    image: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.7.2
    restart: unless-stopped
    ports:
      - "9009:4050"
    volumes:
      - /tmp/simple-docker/back:/tmp/back
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
